#ifndef DEBUGAPPENDER_H_
#define DEBUGAPPENDER_H_

namespace CecilStLabs
{
   /**
    * Appender Interface used to abstract various appenders.
    */
   class IAppender
   {
      public:

         /**
          * Appends the specified message to the appenders output.
          * Intended to be implemented by the concrete sub-class.
          */
         virtual void Append(std::string message) = 0;

      private:

         /**
          * NOTE: the interface's constructor and destructor, copy constructor
          * and assignment operator are defined empty and private to ensure that
          * they cannot be automatically generated by the compiler and they cannot
          * be defined anywhere else.
          */

         IAppender() { };
         virtual ~IAppender() { };
         IAppender(IAppender* app) { };
         IAppender& operator=(IAppender& app) { return *this; };
   };

}
#endif
